version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: 'docker/php/Dockerfile'
    volumes:
      - php-files:/workdir
      - type: bind
        source: ./.env
        target: /workdir/.env
      - type: bind
        source: ./storage/logs
        target: /workdir/storage/logs
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - net
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: '${TIMEZONE}'
  web:
    build:
      context: docker/nginx
      dockerfile: 'Dockerfile'
    volumes:
      - php-files:/workdir
    ports:
      - '${APP_PORT:-80}:80'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - net
    depends_on:
      - app
    environment:
      TZ: '${TIMEZONE}'
  db:
    image: 'postgres'
    restart: always
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - net
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "{DB_DATABASE}" ]
      retries: 10
      timeout: 30s

networks:
  net:
    driver: bridge
volumes:
  php-files:
    driver: local
  db:
    driver: local

