services:
  app:
    build:
      context: .
      dockerfile: 'docker/php/Dockerfile'
    volumes:
      - php-files:/workdir
      - type: bind
        source: ./.env
        target: /workdir/.env
      - type: bind
        source: ./storage/logs
        target: /workdir/storage/logs
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - net
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: &timezone "Europe/Lisbon"
  web:
    build:
      context: docker/nginx
      dockerfile: 'Dockerfile'
    volumes:
      - php-files:/workdir
    ports:
      - '${APP_PORT:-80}:80'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - net
    depends_on:
      - app
    environment:
      TZ: *timezone
  db:
    build:
      context: docker/mysql
      dockerfile: 'Dockerfile'
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: *timezone
    volumes:
      - 'db-files:/var/lib/mysql'
    networks:
      - net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 10
      timeout: 30s
  phpmyadmin:
    image: phpmyadmin:5-apache
    restart: always
    depends_on:
      db:
        condition: service_healthy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${PHPMYADMIN_PORT:-8080}:80'
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: db
      PMA_PORT: '${DB_PORT:-3306}:3306'
    networks:
      - net
networks:
  net:
    driver: bridge
volumes:
  php-files:
    driver: local
  db-files:
    driver: local

