@startuml name platform
left to right direction

actor "User" as user
actor "Security Officer" as so
actor "Data Protection Officer" as dpo
user <|-- so
user <|-- dpo
rectangle "Platform Management" {
  usecase "Login" as UC1
    usecase "Update Own Profile Details & Preferred Language" as UC2
  usecase "Update User Profile Details & Roles" as UC3
  usecase "Define Permanent Contact Point" as UC4
  usecase "Define Security Delegate" as UC5
  usecase "Search for User" as UC6
}
user --> UC1
user --> UC2
so --> UC6
so --> UC3
so --> UC4
so --> UC5

newpage
left to right direction
actor "Asset Manager" as am
actor "Security Officer" as so
actor "Data Protection Officer" as dpo
am <|-- so
rectangle "Asset Management" {
  usecase "Search for User" as UC0
  usecase "View Assets" as UC1
  usecase "Create Asset" as UC2
  usecase "(Re-)Assign User to Asset" as UC3
  usecase "Edit Attributes of Asset" as UC4
  usecase "Remove Asset" as UC5
  usecase "Create Asset Types" as UC8

}
UC3 .> UC0 : includes
dpo -->UC1
am -->UC1
so --> UC2
so -->UC3
so --> UC5
am --> UC4
so --> UC8

newpage
actor "Asset Manager" as am
actor "Security Officer" as so
am <|-- so
rectangle "Risk Management"{
    usecase "Create Threats" as UC1
    usecase "Create Controls" as UC6
    usecase "Appreciate/Valuate Asset" as UC2
    usecase "Define Asset Threats" as UC3
    usecase "Define Countermeasures for Asset Threats" as UC4
    usecase "(In)Validate Treatments for Asset Threats" as UC5
    usecase "Accept Remaining Risk for Threat" as UC7
}
so --> UC1
so --> UC6
am --> UC3
am --> UC7
note on link
Only if the control for the threat was
already validated by the security officer
end note
am --> UC2
note on link
Only if the asset is valued
end note
am --> UC4
note on link
Only if the threats for an asset are defined
end note
so --> UC5
note on link
Only if the user already defined
countermeasures for all threats
end note

newpage
left to right direction
actor "Security Officer" as so
rectangle "Report Generation"{
    usecase "Generate Network Dependency Graph" as UC1
    usecase "Generate Asset Spreadsheet" as UC2
    usecase "Generate Permanent Contact Point Spreadsheet" as UC3
    usecase "Generate Security Delegate Spreadsheet" as UC4
    usecase "Generate Filled Report" as UC5
}
so --> UC1
so --> UC2
so --> UC3
so --> UC4
so --> UC5
@enduml
